
DROP TABLE IF EXISTS ShoppingCartItems;
DROP TABLE IF EXISTS ShoppingCarts;
DROP TABLE IF EXISTS OrderItems;
DROP TABLE IF EXISTS Orders; 
DROP TABLE IF EXISTS PromoCodes;
DROP TABLE IF EXISTS Movies;
DROP TABLE IF EXISTS Genres;
DROP TABLE IF EXISTS Actors;
DROP TABLE IF EXISTS Users;
